requirements.txt
This PR provides a solution to have the custom django-imagekit fork as dependency to the vespawatch setup. Tested and working on DEV .
=> Add https call

deployment/setup.md, djangoproject/settings/settings.py, djangoproject/settings/settings_dev.py, djangoproject/settings/settings_prd.py, djangoproject/settings/settings_uat.py
PR adjusts the log formatting of django logs to cloudwatch and updates the related setup documentation.
=> Log formatting

deployment/README.md, djangoproject/settings/settings.py
This PR extends the existing deployment documentation to provide the technical maintainers with additional guidance on database exports and restoring.
=> Update deployment documentation database management

vespawatch/management/commands/inaturalist_sync.py
Current logs coming from the inaturalist sync job are rather verbose due to the line printing all `inat_obs_data` json data. Removing this line.
=> Cron logs patch

vespawatch/admin.py
=> 447 add search field to admin

assets/js/iasset.js, pages/nl/report-nest-form.md
=> Update nest form

assets/js/iasset.js
Phone and email validation messages
=> Phone and email validation messages

assets/js/iasset.js
If geolocation not allowed - go to default location
=> If geolocation not allowed - go to default location

assets/js/iasset.js
=> Changed object id

assets/js/iasset.js
Fix in marker move event when location allowed
=> Fix in marker move event when location allowed

_data/nl/eradicators.tsv
Because we are unsure how the header of the eradicator table will be translated, we've decided to first add the new eradicator from #510 and then continue with #513
=> Add single eradicator

_data/nl/eradicators.tsv
=> Update eradicator table

pages/nl/eradicators.md, pages/nl/faq.md, pages/nl/report-nest.md
Dag Pieter,
Is het mogelijk om deze wijzigingen na te kijken op spelfouten en goed te keuren? 
Bedankt,
Jasmijn
Als je vragen of suggesties hebt over deze aanpassingen, kan je deze aan Sanne richten?
=> 514 gh pages

pages/nl/eradicators.md
Zie ook opmerking https://github.com/inbo/vespa-watch/pull/516/files#r1281810208
Gebruikers kunnen op meerdere manieren op de lijst met bestrijders terecht komen. De eerste zin moet duidelijk maken wat de pagina is. Pas in de 2de paragraaf zou ik verwijzen naar het rapporteerformulier. Eventueel kan aangevuld worden met "We bezorgen je zo snel mogelijk een validatie via email."
=> Link slechts 1 keer naar nestformulier op lijst bestrijders

_data/nl/eradicators.tsv
I added a new eradicator to the list https://vespawatch.be/report-nest/
=> Added Johan Dejonkheere to list

_data/nl/eradicators.tsv
Added a new eradicator Wespenverdelg.be to the list https://vespawatch.be/eradicators/
=> Added Wespenverdelg.be to list

_data/nl/eradicators.tsv
Added eradicator Beehome in the list of eradicators https://vespawatch.be/eradicators/
=> Added eradicator Beehome

_data/nl/eradicators.tsv
Added De wespenkiller to the eradicator list
=> Added De wespenkiller to list

_data/nl/eradicators.tsv
Added three new eradicators to the list
=> Added three new eradicators

_data/nl/eradicators.tsv
Added Jan Pauwels as a new eradicator to the list
=> Added Jan Pauwels to list

_data/nl/eradicators.tsv
Added Wegwesp to the list of eradicators
=> Added Wegwesp to list
